services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: serp-hawk-backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
    container_name: serp-hawk-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
